Updatedb
bitmark-inc/bitmark-node-upgrader pull request #2
Opened 2019-04-15 02:45 UTC by pieceofr

The purpose of this pull request is to get the latest chain db information and fetch latest chain db according to information. The updater will backup old database and then use downloaded database. 
There were several commits are fix path issue. This is because there are path errors when we run in the docker. Also go rename or delete package does not handle directory overwrite well.

2019-04-17 06:00 UTC, araujobsd requested changes

2019-04-17 06:00 UTC, araujobsd commented on awsService/awsUtil.go
> +	//"errors"
Please remove the comment.

2019-04-17 06:00 UTC, araujobsd commented on awsService/awsUtil.go
> +//NewS3Service : Create a new session of S3 service
Add a space between // and NewS3Service comment.

2019-04-17 06:00 UTC, araujobsd commented on awsService/awsUtil.go
> +
Blank line here! It can be removed.

2019-04-17 06:00 UTC, araujobsd commented on awsService/data/uploads3.sh
> +#!bin/bash
It should be /bin/bash instead of bin/bash.
Also it is better to use env for shebangs, the only time we should use an absolute path in a shebang is when your script isn't meant to be portable.

2019-04-17 06:00 UTC, araujobsd commented on awsService/install.sh
> +#!bin/bash
It should be /bin/bash instead of bin/bash.
Also it is better to use env for shebangs, the only time we should use an absolute path in a shebang is when your script isn't meant to be portable.

So if you use env, your script probably will run on any OS that supports bash.

2019-04-17 06:00 UTC, araujobsd commented on awsService/main.go
> +type LatestChain struct {
Please, put the structure at the top of the file.

2019-04-17 06:00 UTC, araujobsd commented on awsService/main.go
> +func main() {
func main() should be the last func in this file.

2019-04-17 06:00 UTC, araujobsd commented on awsService/main.go
> +	if err != nil && ret == nil {
Here if you have a return error from getLatestDBInfo() it is likely ret will be useless, isn't it?

2019-04-17 06:00 UTC, araujobsd commented on db_test.go
> +var appBaseDir = filepath.Join(userHomeDir(), "bitmark-node-data-test")
Why not use var()?

2019-04-17 06:00 UTC, araujobsd commented on main.go
> +var userPath UserPath
Why not use var()?

2019-04-17 06:00 UTC, araujobsd commented on path.go
> +func (u *UserPath) GetLogPath(network string) (path string) {
Why not have a func called GetPath that returns Datapath and LogPath at once instead of repeat code?

2019-04-17 06:00 UTC, araujobsd commented on path.go
> +func (d *DockerPath) GetLogPath(network string) (path string) {
Same here!

2019-04-17 06:00 UTC, araujobsd commented on path_test.go
> +var mockUserCorrectDir = map[string]string{
variables declaration should appears before any func declaration. Also you could use var()!

2019-04-17 06:00 UTC, araujobsd commented on path_test.go
> +		//	BaseDir:        "/home/pieceofr2/bitmark-node-data-test",
Delete comment!

2019-04-17 06:00 UTC, araujobsd commented on path_test.go
> +
Delete blank line!

2019-04-17 06:00 UTC, araujobsd commented on service.go
> +			var newContainerConfig *CreateContainerConfig
Please, don't declare variables in the middle of the code, declare it at the beginning of the function.

2019-04-17 06:00 UTC, araujobsd commented on updateDB.go
> +		if latestVer != r.CurrentDBVer {
If both if statement returns false, false why not use an OR and check both err and latestVer within only one if statement.

2019-04-17 06:00 UTC, araujobsd commented on updateDB.go
> +	var latestChain LatestChain
Declare variables in the middle of the code isn't a good approach!

2019-04-17 06:00 UTC, araujobsd commented on updateDB.go
> +	if !mainnet {
Will be mainnet nil? If so, better do explicit mainnet == nil

2019-04-17 06:00 UTC, araujobsd commented on util.go
> +func userHomeDir() string {
If this func will be only used for WINDOWS, would be more clear to add a comment or rename the func to something more explicit such as userHomeDirWindows().

2019-04-17 06:00 UTC, araujobsd commented on util.go
> +	if 0 == len(homeDir) {
It should be if len(homeDir) == 0 and not the opposite, you are validating len(homeDir) and not 0 itself.

2019-04-18 02:22 UTC, hxw commented on awsService/data/uploads3.sh
> +#!bin/bash
is it really bash specific? if not #!/bin/sh is preferable

2019-04-18 02:23 UTC, hxw commented on awsService/install.sh
> +#!bin/bash
#!/bin/sh is better if script is Posix compatible

2019-04-18 08:31 UTC, araujobsd commented on awsService/data/uploads3.sh
> +#!bin/bash
You can use something like this: #!/usr/bin/env sh

2019-04-18 09:19 UTC, araujobsd commented on updateDB.go
> +		if latestVer != r.CurrentDBVer {
if err != nil || latestVer != r.CurrentDBVer { 
      return false, false
}

2019-05-07 07:16 UTC, merged